import "./global.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <title>Custom NextJS app</title>
            </head>
            <body>{children}</body>
        </html>
    )
}
